SELECT o.ANIMAL_ID AS ANIMAL_ID, o.NAME AS NAME
FROM ANIMAL_INS AS i RIGHT OUTER JOIN ANIMAL_OUTS AS o ON i.ANIMAL_ID = o.ANIMAL_ID
WHERE i.ANIMAL_ID IS NULL AND o.ANIMAL_ID IS NOT NULL
ORDER BY o.ANIMAL_ID ASC;