WITH RECURSIVE RCSV_GENERATION AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, E.PARENT_ID, R.GENERATION+1
    FROM ECOLI_DATA E
    JOIN RCSV_GENERATION R ON E.PARENT_ID = R.ID
)
SELECT  COUNT(*) AS COUNT, R.GENERATION AS GENERATION
FROM (
    SELECT *
    FROM ECOLI_DATA
    WHERE
        ID NOT IN (
            SELECT DISTINCT (IFNULL(PARENT_ID, 0))
            FROM ECOLI_DATA
    )
) NC
JOIN RCSV_GENERATION R
ON NC.ID = R.ID
GROUP BY R.GENERATION
ORDER BY R.GENERATION