SELECT ins.NAME AS NAME, ins.DATETIME AS DATETIME
FROM ANIMAL_INS as ins LEFT JOIN ANIMAL_OUTS as outs ON ins.ANIMAL_ID = outs.ANIMAL_ID
WHERE outs.ANIMAL_ID IS NULL
ORDER BY ins.DATETIME ASC
LIMIT 3;