SELECT p.PRODUCT_ID AS PRODUCT_ID, p.PRODUCT_NAME AS PRODUCT_NAME,
SUM(o.AMOUNT*p.PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT AS p JOIN FOOD_ORDER AS o ON p.PRODUCT_ID = o.PRODUCT_ID
WHERE DATE_FORMAT(o.PRODUCE_DATE, '%Y-%m') = '2022-05'
GROUP BY p.PRODUCT_ID
ORDER BY SUM(o.AMOUNT*p.PRICE) DESC, p.PRODUCT_ID ASC;